### ISSUE TITLE
Prioritization

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/bibframe-work-validation#1]
Prioritization for reverse engineering, documentation, evalutation:
- [ ] Work
  - [x] reverse engineer / documentation
  - [x] spec from metadata folks
  - [ ] validation tests
    - [x] outlined
    - [x] some tests written
- [ ] Instance
  - [x] reverse engineer / documentation
  - [ ] spec from metadata folks
  - [ ] validation tests
    - [x] outlined
    - [x] some tests written
- [ ] Person
  - [x] reverse engineer / documentation
  - [x] spec from metadata folks
  - [ ] validation tests
    - [ ] outlined (saved for @jgreben for now)
    - [ ] some tests written (saved for @jgreben for now)
- [ ] Publisher
  - [x] reverse engineer / documentation 'publication'
  - [ ] spec from metadata folks
  - [ ] validation tests
    - [x] outlined
    - [x] some tests written
- [ ] Title
  - [ ] reverse engineer / documentation
  - [ ] spec from metadata folks
  - [ ] validation tests
    - [ ] outlined
    - [ ] some tests written (with Work)
- [ ] Identifier
  - [ ] reverse engineer / documentation (in progress)
  - [ ] spec from metadata folks (requested 2015-09-24 - in progress)
  - [ ] validation tests
    - [ ] outlined
    - [ ] some tests written (with Work)
- [ ] Organization
  - [ ] reverse engineer / documentation
  - [ ] spec from metadata folks
  - [ ] validation tests
    - [ ] outlined
    - [ ] some tests written (with Work)
- [x] instanceOf
- [ ] label
- [ ] identifier
- [ ] relatedTo
  - [x] relatedResource
  - [x] relatedWork
- [x] publisher (currently bundled with publication)

**Comment by jgreben** [comment]
See #33. Tests will be written upon request.
