### ISSUE TITLE
create tests for each basic SW property desired

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/bibframe-work-validation#25]
https://consul.stanford.edu/display/DLSSDOCS/Minimum+Requirements+for+Non-MARC+Descriptive+Metadata+in+SearchWorks

Do required properties first.  If the "highly recommended" properties won't be easy to do, make separate issue(s) to do them.

See http://id.loc.gov/ontologies/bibframe.html and http://id.loc.gov/ontologies/bibframe-category.html

**Comment by jgreben** [comment]
Here is what will be my focus based on the linked document above. Fortunately, some of the tests for Titles based on the LOC specs already include baked in tests for dates and resource types (form/genre):

- [x] Titles
- [ ] Creators
- [x] Types of resource
   - [ ] need test for genre/form from 008[24-27]
- [ ] Dates
   - [x] need test for pub date from 008[7-14]
   - [ ] need test for pub date from 260
- [ ] Language (041)
- [ ] Extent (533, 534)
- [ ] Subjects (6XX)
- [ ] Identifiers ( ISBN, ISSN, LCCN, etc.)

**Comment by ndushay** [comment]
I also wouldn't turn my nose up at tests for a couple of different identifiers such as ISBN, ISSN, LCCN, etc.

**Comment by jgreben** [comment]
```
RDF for names
<resource>	bf:contribution     [	a 	bf:Contribution ;
bf:agent     [	a	bf: Person, Organization, etc.  
				rdfs:label		“label from Process 1.3”;
				identifiedBy   [
					rdf:value    	“content after (…) in $0 or $w”;
					bf:source	“content of (...) in $0 or $w” ] ;	
				bflc:nameXXMatchKey     “string from Process 1.1”;
				bflc:nameXXMarcKey	“string from Process 1.2” ] ;
bf:role		[rdfs:label    “…”  ]			see Process 1.4	
				bf:code	[rdf:value     “…”   ]   ;		see Process 1.4
		If code from ID, then instead:
			bf:role		URI for role
```

**Comment by ndushay** [comment]
Josh, I was thinking something like this, sort of.  Note that the absolute specifics of which thingies is less important than the notion of exemplars in multiple flavors.   This is the "bf2" view, as opposed to the "marc" view.   The consul page is a "mods" view, which is perhaps less helpful.

My original thought for the validator was to focus more on the "bf" view than the marc view.  That may or may not make the most sense.  Or maybe we need both ... I dunno.  All the possible subfields in a marc [245] and all the diff values in indicators and subfields that would imply conversion to diff bf properties --  should be tested ... somewhere.  Similarly, all the possible bf classes and properties should get tested ... somewhere.   One would HOPE that "somewhere" is part of the test suite accompanying a converter.  :-P

- [x] Titles:
   - [x] bf:mainTitle
   - [x] bf:subtitle
- [ ] Creators
   - [ ] bf:Agent with some role
   - [ ] bf:Agent with diff role
   - [ ] a person
   - [ ] a meeting or organization
- [ ] Type of Resource
   - [ ] bf:Content (for bf:Work)
   - [x] bf:GenreForm
   - [ ] bf:Media?
   - [ ] bf:Carrier, e.g.
       - [ ] bf:BookFormat
       - [ ] bf:Sound|Projection|VideoCharacteristic
- [ ] Date, e.g.
   - [x] bf:originDate (for bf:Work)
   - [ ] bf:copyrightDate
   - [ ] bf:capture  (date)
- [ ] Language
   - [ ] bf:language
   - [ ] bf:translation ?
- [ ] "Extent", e.g.
   - [ ] bf:extent
   - [ ] bf:dimensions
- [ ] Subject
   - [ ] bf:subject
   - [ ] bf:classification
   - [ ] bf:classificationPortion
- [ ] Identifiers
   - [ ] ISBN
   - [ ] LCCN

**Comment by ndushay** [comment]
See https://consul.stanford.edu/display/LD4P/Bibframe+2.0+to+Solr+Mapping

**Comment by jgreben** [comment]
Closed via https://github.com/sul-dlss/ld4p/issues/67
